/*
ENCRIPTAR LAS COLUMNAS QUE CONTENGAN DATOS SENSIBLES EN NUESTRO SISTEMA
*/

USE CentroComercialT

GO

CREATE MASTER KEY ENCRYPTION BY   
PASSWORD = '8734YFUEYW78345';

GO

---------------------------------------------------------
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH87374YR6E7 
   WITH SUBJECT = 'Clava de seguridad Tienda de abarrotes';  
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_0985  
    WITH ALGORITHM = AES_256  
    ENCRYPTION BY CERTIFICATE JSH87374YR6E7 ;  
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE empleado 
    ADD telefonoEncriptado varbinary(128);   
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_0985  
   DECRYPTION BY CERTIFICATE JSH87374YR6E7;

-- CLOSE SYMMETRIC KEY SSN_Key_0985
-- ENCRIPTAR LOS DATOS DE 'telefono' en 'telefonoEncriptado'
UPDATE empleado
SET telefono = EncryptByKey(Key_GUID('SSN_Key_0985'), telefonoEncriptado) FROM empleado;

GO 

-- ELIMINAR LA COLUMNA QUE CONTIENE LOS DATOS DESCENCRIPTADOS
ALTER TABLE empleado DROP COLUMN telefono

GO

-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_0985;
-- RENOMBRAR LA COLUMNA
EXEC sp_rename 'empleado.telefonoEncriptado', 'telefono', 'COLUMN'

GO

----------------------------------------------------------------------------------------------------------------------------------
-- CIFRAR NACIMIENTO DE EMPLEADO
CREATE MASTER KEY ENCRYPTION BY   
PASSWORD = '8734YFUEYW78345';

-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH898374HFYE 
   WITH SUBJECT = 'Clava de seguridad para nacimiento en empleado';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_2498  
    WITH ALGORITHM = AES_256  
    ENCRYPTION BY CERTIFICATE JSH898374HFYE;  
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE empleado 
    ADD nacimientoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_2498 DECRYPTION BY CERTIFICATE JSH898374HFYE;

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'nacimientro' en 'ColumnaEncriptada'
UPDATE empleado SET nacimientoEncriptado = EncryptByKey(Key_GUID('SSN_Key_2498'), CONVERT(VARBINARY(128),nacimiento)) FROM empleado;
GO 

-- ELIMINAR LA COLUMNA QUE CONTIENE LOS DATOS DESCENCRIPTADOS
ALTER TABLE empleado DROP COLUMN nacimiento 

GO

ALTER TABLE empleado DROP CONSTRAINT ckNacimiento
-- SELECCIONAR LAS COLUMNAS Y DESCENCRIPTAR LOS DATOS EN UNA NUEVA COLUMNA

GO

-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_2498; 

GO

-------------------------------------------------- ENCRIPTAR DATOS DEL EMPLEADO -----------------------------------------------------
-- ENCRIPTAR CORREO EMPLEADO
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH876347LSIE  WITH SUBJECT = 'Clava de seguridad para correo en empleado';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_2394 WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE JSH876347LSIE;
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE empleado ADD correoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_2394 DECRYPTION BY CERTIFICATE JSH876347LSIE;

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'columna2' en 'ColumnaEncriptada'
UPDATE empleado SET correoEncriptado = EncryptByKey(Key_GUID('SSN_Key_2394'), CONVERT(VARBINARY(128),correo)) FROM empleado;
GO 


-- ELIMINAR LA COLUMNA QUE CONTIENE LOS DATOS DESCENCRIPTADOS
ALTER TABLE empleado DROP COLUMN correo

GO

-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_2394; 
-- RENOMBRAR LA COLUMNA
EXEC sp_rename 'empleado.correoEncriptado', 'correo', 'COLUMN'

GO
-------------------------------------------------- ENCRIPTAR DATOS DEL CLIENTE -----------------------------------------------------
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH34UDW6T3E  WITH SUBJECT = 'Clava de seguridad para telefono en cliente';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_3987 WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE JSH34UDW6T3E;
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE cliente ADD telefonoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_3987 DECRYPTION BY CERTIFICATE JSH34UDW6T3E;

GO

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'telefono' en 'telefonoEncriptado'
UPDATE cliente SET telefonoEncriptado = EncryptByKey(Key_GUID('SSN_Key_3987'), CONVERT(VARBINARY(128),telefono)) FROM cliente;

GO 

ALTER TABLE cliente DROP COLUMN telefono

GO

-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_3987; 
GO

-------------------------------------------------- ENCRIPTAR DATOS DEL CLIENTE -----------------------------------------------------
-- ENCRIPTAR NACIMIENTO CLIENTE
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH76WERD5SW  WITH SUBJECT = 'Clava de seguridad para nacimiento en cliente';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_7629 WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE JSH76WERD5SW;
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE cliente ADD nacimientoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_7629 DECRYPTION BY CERTIFICATE JSH76WERD5SW;

GO

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'nacimiento' en 'nacimientoEncriptado'
UPDATE cliente SET nacimientoEncriptado = EncryptByKey(Key_GUID('SSN_Key_7629'), CONVERT(VARBINARY(128), nacimiento)) FROM cliente;

GO 

ALTER TABLE cliente DROP COLUMN nacimiento

GO

 
-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_7629; 
-- RENOMBRAR LA COLUMNA		
EXEC sp_rename 'cliente.nacimientoEncriptado', 'nacimiento', 'COLUMN'
GO

-------------------------------------------------- ENCRIPTAR DATOS DEL CLIENTE -----------------------------------------------------
-- ENCRIPTAR NACIMIENTO CLIENTE
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH8374HDYS  WITH SUBJECT = 'Clava de seguridad para correo en cliente';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_2309 WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE JSH8374HDYS;
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE cliente ADD correoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_2309 DECRYPTION BY CERTIFICATE JSH8374HDYS;

GO

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'correo' en 'correoEncriptado'
UPDATE cliente SET correoEncriptado = EncryptByKey(Key_GUID('SSN_Key_2309'), CONVERT(VARBINARY(128), correo)) FROM cliente;

GO 

ALTER TABLE cliente DROP COLUMN correo

GO
 
-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_2309; 
-- RENOMBRAR LA COLUMNA
EXEC sp_rename 'proveedor.correoEncriptado', 'correo', 'COLUMN'
GO

-------------------------------------------------- ENCRIPTAR DATOS DEL PROVEEDOR ----------------------------------------------------
-- ENCRIPTAR TELEFONO PROVEEDOR
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH8238HSANB  WITH SUBJECT = 'Clava de seguridad para telefono en proveedor';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_2439 WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE JSH8238HSANB;
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE proveedor ADD telefonoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_2439 DECRYPTION BY CERTIFICATE JSH8238HSANB;

GO

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'telefono' en 'telefonoEncriptado'
UPDATE proveedor SET telefonoEncriptado = EncryptByKey(Key_GUID('SSN_Key_2309'), CONVERT(VARBINARY(128), telefono)) FROM proveedor;

GO 

-- ELIMINAR LA COLUMNA QUE CONTIENE LOS DATOS DESCENCRIPTADOS
ALTER TABLE proveedor DROP COLUMN telefono

GO

-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_2439;

GO

-- RENOMBRAR LA COLUMNA
EXEC sp_rename 'proveedor.telefonoEncriptado', 'telefono', 'COLUMN'

GO

-- NUNCA DEJAR LA CLAVE ABIERTA
CLOSE SYMMETRIC KEY SSN_Key_2439; 

GO

-------------------------------------------------- ENCRIPTAR DATOS DEL PROVEEDOR ----------------------------------------------------
-- ENCRIPTAR CORREO PROVEEDOR
-- CREAR EL CERTIFICADO (EMPLEADO)
CREATE CERTIFICATE JSH8BCHWGE623  WITH SUBJECT = 'Clava de seguridad para correo en proveedor';
GO  

-- CREAR LA CLAVE SIMETRIC (EMPLEADO)
CREATE SYMMETRIC KEY SSN_Key_0943 WITH ALGORITHM = AES_256 ENCRYPTION BY CERTIFICATE JSH8BCHWGE623;
GO  

-- CREAR UNA COLUMNA CON LOS DATOS ENCRIPTADOS
ALTER TABLE proveedor ADD correoEncriptado varbinary(128);
GO  

-- ABRIR LA CLAVE CREADA CON SU CERTIFICADO
OPEN SYMMETRIC KEY SSN_Key_0943 DECRYPTION BY CERTIFICATE JSH8BCHWGE623;

-- CLOSE SYMMETRIC KEY SSN_Key_2498
-- ENCRIPTAR LOS DATOS DE 'correo' en 'correoEncriptado'
UPDATE proveedor SET correoEncriptado = EncryptByKey(Key_GUID('SSN_Key_0943'), CONVERT(VARBINARY(128), correo)) FROM proveedor;
GO 

-- ELIMINAR LA COLUMNA QUE CONTIENE LOS DATOS DESCENCRIPTADOS
ALTER TABLE proveedor DROP COLUMN correo
GO
 
-- CERRAR LA CLAVE 
CLOSE SYMMETRIC KEY SSN_Key_0943;
GO

-- RENOMBRAR LA COLUMNA
EXEC sp_rename 'proveedor.correoEncriptado', 'correo', 'COLUMN'

